# Rust-specific Flazel derivation builder
#
# Wraps the core mkFlazelDerivation with Rust toolchain configuration.
#
# Usage:
#   cfg = flazel.lib.rust.mkConfig { inherit pkgs; };
#   build = flazel.lib.rust.mkDerivation {
#     inherit pkgs cfg caches;
#     name = "my-project";
#     src = ./.;
#     bazelCommand = "build --config=nix //...";
#     installPhase = "cp -rL bazel-bin/* $out/";
#   };
#
{
  pkgs,
  name,
  cfg,
  caches,
  src,
  bazelCommand,
  installPhase,
  bazel ? pkgs.bazel,
  flazelPath ? null,
  extraNativeBuildInputs ? [ ],
  extraBuildInputs ? [ ],
}:
let
  coreDeriv = import ../core/derivation.nix;

  rustDepsSetup = ''
        mkdir -p .nix-bazel-deps/toolchains
        ln -s ${cfg.bazelNixDeps}/toolchains/${cfg.toolchainName} .nix-bazel-deps/toolchains/${cfg.toolchainName}

        echo "${cfg.toolchainName}" >> .nix-bazel-deps/.toolchain-marker

        cat >> .nix-bazel-deps/.bazelrc.nix << 'BAZELRC'
    # Auto-generated by nix build - DO NOT EDIT
    ${
      pkgs.lib.concatMapStrings (target: ''
        build --extra_toolchains=@local_config_rust_${cfg.toolchainName}//:rust_toolchain_${
          builtins.replaceStrings [ "-" ] [ "_" ] target
        }
      '') cfg.targets
    }${coreDeriv.mkBazelrcFooter { inherit flazelPath caches; }}BAZELRC
  '';
in
coreDeriv.mkFlazelDerivation {
  inherit
    pkgs
    name
    src
    caches
    bazel
    flazelPath
    bazelCommand
    installPhase
    ;

  extraDepsSetup = rustDepsSetup;

  nativeBuildInputs = [
    cfg.rustToolchain
  ]
  ++ extraNativeBuildInputs;

  buildInputs = extraBuildInputs;
}
