# BCR (Bazel Central Registry) caching and non-BCR dependency management
#
# Provides functions to:
# - Prefetch and cache BCR module dependencies from MODULE.bazel.lock
# - Override non-BCR Bazel *modules* (bazel_dep with no registry entry) via
#   --override_module in .bazelrc.nix
# - Seed the offline repo cache with archives the lock cannot express
#   (extraArchives), keyed by sha256
#
# Usage:
#   caches = flazel.lib.mkBcrCaches {
#     inherit pkgs;
#     lockFile = flazel.lib.parseLockFile ./MODULE.bazel.lock;
#     # Bazel *modules* with no BCR registry entry (bazel_dep name has no version):
#     nonBcrDeps = [
#       { name = "foo"; url = "..."; hash = "..."; stripPrefix = "..."; }
#     ];
#     # Archives the lock cannot express, seeded into the repo cache by sha256:
#     #   - root-module use_repo_rule http_archive/http_file deps (declare them in
#     #     MODULE.bazel with their integrity; list the same url+sha256 here so the
#     #     archive resolves offline). This is the canonical way to make a
#     #     use_repo_rule repo offline; --override_repository does NOT work for
#     #     them (it cannot match the `_main~_repo_rules~<name>` canonical name).
#     #   - globally registered toolchains fetched via download_and_extract on a
#     #     hardcoded URL (e.g. aspect_bazel_lib's bats, rules_python interpreters).
#     extraArchives = [ { url = "..."; sha256 = "..."; } ];
#   };
#   # caches.bazelRepoCache - content-addressable archive cache (BCR + extraArchives)
#   # caches.bazelRegistryCache - BCR registry metadata + overlay cache
#   # caches.nonBcrOverrideFlags - .bazelrc.nix --override_module lines
#
{
  # Parse a MODULE.bazel.lock file safely
  parseLockFile =
    path:
    let
      content = if builtins.pathExists path then builtins.readFile path else "";
      # Check if content starts with '{' (valid JSON object)
      isValidJson = builtins.stringLength content > 0 && builtins.substring 0 1 content == "{";
    in
    if isValidJson then builtins.fromJSON content else { registryFileHashes = { }; };

  # Generate BCR caches from lock file
  mkBcrCaches =
    {
      pkgs,
      lockFile,
      nonBcrDeps ? [ ],
      extraArchives ? [ ],
    }:
    let
      parseSourceUrl =
        url:
        let
          parts = builtins.match "https://bcr.bazel.build/modules/([^/]+)/([^/]+)/source.json" url;
        in
        if parts != null then
          {
            name = builtins.elemAt parts 0;
            version = builtins.elemAt parts 1;
            sourceJsonUrl = url;
            sourceJsonHash = lockFile.registryFileHashes.${url};
            baseUrl = "https://bcr.bazel.build/modules/${builtins.elemAt parts 0}/${builtins.elemAt parts 1}";
          }
        else
          null;

      sourceJsonUrls = builtins.filter (url: builtins.match ".*source\\.json$" url != null) (
        builtins.attrNames (lockFile.registryFileHashes or { })
      );

      modules = builtins.filter (x: x != null) (map parseSourceUrl sourceJsonUrls);

      fetchSourceJson =
        module:
        let
          sourceJson = builtins.fetchurl {
            url = module.sourceJsonUrl;
            sha256 = module.sourceJsonHash;
          };
          sourceInfo = builtins.fromJSON (builtins.readFile sourceJson);
        in
        module
        // {
          archiveUrl = sourceInfo.url;
          archiveIntegrity = sourceInfo.integrity;
          patches = sourceInfo.patches or { };
          # BCR "overlay" files (a BUILD.bazel/MODULE.bazel the registry layers
          # onto upstream sources that ship no Bazel build, e.g. zlib-ng). Served
          # at <baseUrl>/overlay/<file>; fetched at repo-fetch time, so absent
          # from registryFileHashes and invisible to the offline build unless
          # cached explicitly below.
          overlay = sourceInfo.overlay or { };
        };

      modulesWithSources = map fetchSourceJson modules;

      # Download-style repos generated by module extensions (e.g. rules_rust's
      # process_wrapper crate "tinyjson" or crate_universe crates; rules_kotlin's
      # kotlin_compiler_repository / ksp_compiler_plugin_repository). These are
      # fetched from crates.io / github, not the BCR, so they are absent from
      # registryFileHashes and must be cached separately for offline builds.
      extensionArchives =
        let
          exts = lockFile.moduleExtensions or { };
          # Each extension value holds one result per platform (usually just
          # "general"), each with a generatedRepoSpecs attrset.
          specsOf =
            ext:
            builtins.concatMap (result: builtins.attrValues (result.generatedRepoSpecs or { })) (
              builtins.attrValues ext
            );
          allSpecs = builtins.concatLists (map specsOf (builtins.attrValues exts));
          toArchive =
            spec:
            let
              attrs = spec.attributes or { };
              url = attrs.url or (if attrs ? urls && attrs.urls != [ ] then builtins.head attrs.urls else null);
              sha256 = attrs.sha256 or null;
            in
            # Any extension repo that downloads a single url with a hex sha256 is
            # cacheable, whatever its rule class. Bazel keys the repo cache by the
            # archive's sha256 + url, so http_archive (rust crates, …) and wrapper
            # rules like kotlin_compiler_repository / ksp_compiler_plugin_repository
            # are handled identically; restricting to http_archive silently dropped
            # the latter and broke offline (hermetic) builds that load rules_kotlin.
            if url != null && sha256 != null then { inherit url sha256; } else null;
        in
        builtins.filter (a: a != null) (map toArchive allSpecs);

      fetchExtensionArchive =
        a:
        pkgs.fetchurl {
          inherit (a) url sha256;
        };

      fetchModuleArchive =
        mod:
        pkgs.fetchurl {
          url = mod.archiveUrl;
          name = "${mod.name}-${mod.version}.tar.gz";
          hash = mod.archiveIntegrity;
        };

      # Fetch a module's BCR `patches` or `overlay` files (subdir = "patches" or
      # "overlay"). source.json lists each as { filename = integrity }, served at
      # <baseUrl>/<subdir>/<filename>: patches are diffs applied to the upstream
      # source; overlay files (e.g. a BUILD.bazel) are layered onto sources that
      # ship no Bazel build. Returns { filename = store-path }.
      fetchModuleFiles =
        subdir: mod:
        builtins.mapAttrs (
          name: hash:
          pkgs.fetchurl {
            url = "${mod.baseUrl}/${subdir}/${name}";
            inherit hash name;
          }
        ) mod.${subdir};

      # Extract a non-BCR module archive into a ready-to-use directory. These are
      # Bazel modules (they carry their own MODULE.bazel + BUILD files), so no
      # BUILD injection is needed. Non-module repos (use_repo_rule http_archive)
      # are handled by extraArchives, not here: see the module header.
      mkExtractedDep =
        dep:
        pkgs.stdenv.mkDerivation {
          name = "bazel-dep-${dep.name}";
          src = pkgs.fetchurl {
            url = dep.url;
            hash = dep.hash;
          };
          sourceRoot = dep.stripPrefix;
          phases = [
            "unpackPhase"
            "installPhase"
          ];
          installPhase = "cp -r . $out";
        };

      # Generate .bazelrc.nix --override_module lines for non-BCR modules.
      nonBcrOverrideFlags = builtins.concatStringsSep "\n" (
        map (dep: "build --override_module=${dep.name}=${mkExtractedDep dep}") nonBcrDeps
      );

      # Bazel keys its content-addressable cache by the hex sha256 of the archive
      # bytes and an id marker by the hex sha256 of the source URL. Both are known
      # at eval time (module/patch integrity is SRI; extension http_archives carry
      # a hex sha256), so convert them here instead of re-reading every archive at
      # build time.
      toHex =
        h:
        if builtins.substring 0 7 h == "sha256-" then
          builtins.convertHash {
            hash = h;
            toHashFormat = "base16";
          }
        else
          h;
      urlHash = url: builtins.hashString "sha256" url;

      bazelRepoCache = pkgs.runCommand "bazel-repo-cache" { } ''
        mkdir -p $out/content_addressable/sha256

        add_to_cache() {
          local file=$1 hash=$2 url_hash=$3
          mkdir -p $out/content_addressable/sha256/$hash
          ln -sf "$file" $out/content_addressable/sha256/$hash/file
          touch $out/content_addressable/sha256/$hash/id-$url_hash
        }

        ${builtins.concatStringsSep "\n" (
          map (
            mod:
            let
              archive = fetchModuleArchive mod;
              patches = fetchModuleFiles "patches" mod;
            in
            ''
              add_to_cache "${archive}" "${toHex mod.archiveIntegrity}" "${urlHash mod.archiveUrl}"
              ${builtins.concatStringsSep "\n" (
                builtins.attrValues (
                  builtins.mapAttrs (
                    name: patch:
                    ''add_to_cache "${patch}" "${toHex mod.patches.${name}}" "${urlHash "${mod.baseUrl}/patches/${name}"}"''
                  ) patches
                )
              )}
            ''
          ) modulesWithSources
        )}

        # Module-extension http_archives (rust crate deps, etc.)
        ${builtins.concatStringsSep "\n" (
          map (
            a: ''add_to_cache "${fetchExtensionArchive a}" "${toHex a.sha256}" "${urlHash a.url}"''
          ) extensionArchives
        )}

        # Caller-supplied { url, sha256 } archives for offline downloads the lock
        # does not expose: e.g. aspect_bazel_lib's bats toolchain, which calls
        # download_and_extract on a hardcoded URL (no generatedRepoSpec to discover).
        ${builtins.concatStringsSep "\n" (
          map (
            a: ''add_to_cache "${fetchExtensionArchive a}" "${toHex a.sha256}" "${urlHash a.url}"''
          ) extraArchives
        )}
      '';

      registryFiles = builtins.filter (url: builtins.match "https://bcr.bazel.build/.*" url != null) (
        builtins.attrNames (lockFile.registryFileHashes or { })
      );

      bazelRegistryCache = pkgs.runCommand "bazel-registry-cache" { } ''
        mkdir -p $out
        ${builtins.concatStringsSep "\n" (
          map (
            url:
            let
              urlPath = builtins.replaceStrings [ "https://bcr.bazel.build/" ] [ "" ] url;
              file = builtins.fetchurl {
                inherit url;
                sha256 = lockFile.registryFileHashes.${url};
              };
            in
            ''
              mkdir -p $out/$(dirname "${urlPath}")
              cp ${file} $out/${urlPath}
              chmod 644 $out/${urlPath}
            ''
          ) registryFiles
        )}

        # Overlay files (modules/<name>/<version>/overlay/<file>) are referenced
        # by source.json but fetched lazily at repo-fetch time, so they never
        # appear in registryFileHashes. Without them the offline build cannot
        # construct overlaid repos (e.g. @zlib-ng~ fails: overlay/BUILD.bazel
        # not found). Cache them from each module's source.json overlay map.
        ${builtins.concatStringsSep "\n" (
          map (
            mod:
            builtins.concatStringsSep "\n" (
              builtins.attrValues (
                builtins.mapAttrs (name: file: ''
                  mkdir -p "$out/modules/${mod.name}/${mod.version}/overlay/$(dirname "${name}")"
                  cp ${file} "$out/modules/${mod.name}/${mod.version}/overlay/${name}"
                  chmod 644 "$out/modules/${mod.name}/${mod.version}/overlay/${name}"
                '') (fetchModuleFiles "overlay" mod)
              )
            )
          ) modulesWithSources
        )}

        find $out -type d -exec chmod 755 {} \;
      '';
    in
    {
      inherit bazelRepoCache bazelRegistryCache nonBcrOverrideFlags;
    };
}
