# Generic Flazel derivation builder (language-agnostic)
#
# Provides a minimal Bazel build derivation without any language-specific
# assumptions. Language-specific modules (cc, rust, etc.) can wrap this
# and add their own configuration.
#
# Usage:
#   build = flazel.lib.mkFlazelDerivation {
#     inherit pkgs;
#     name = "my-project";
#     src = ./.;
#     caches = flazel.lib.mkBcrCaches { ... };
#     bazelCommand = "build //...";
#     installPhase = "cp -rL bazel-bin/* $out/";
#   };
#
rec {
  # Generate .bazelrc.nix lines for flazel module override and non-BCR deps
  mkBazelrcFooter =
    {
      flazelPath ? null,
      caches,
    }:
    (if flazelPath != null then "build --override_module=flazel=${flazelPath}\n" else "")
    + (
      if caches ? nonBcrOverrideFlags && caches.nonBcrOverrideFlags != "" then
        caches.nonBcrOverrideFlags + "\n"
      else
        ""
    );

  # Generate complete .bazelrc.nix content from toolchain registration lines + footer
  mkBazelrcContent =
    {
      toolchainLines,
      flazelPath ? null,
      caches,
    }:
    "# Auto-generated by flazel - DO NOT EDIT\n"
    # Pure bzlmod: disable the legacy WORKSPACE suffix (still on by default in
    # Bazel 7). It pulls deps like bazel_skylib from github via maybe(http_archive),
    # which the BCR cache cannot cover and which fail in the offline sandbox.
    # Set here (not in the build path) so the dev shell and the build resolve
    # dependencies under identical rules.
    + "common --noenable_workspace\n"
    + toolchainLines
    + (mkBazelrcFooter { inherit flazelPath caches; });

  # Generate shell script to set up .nix-bazel-deps directory (core setup).
  # Writes the framework .bazelrc.nix (flazel override + non-BCR overrides plus
  # whatever toolchain registration lines the language module supplies). Language
  # modules add only their symlinks and marker via extraSetup; a bare-core build
  # still gets the flazel override because toolchainLines defaults to empty.
  mkFlazelDepsSetup =
    {
      pkgs,
      caches,
      # Path to flazel source (auto-injected, used for --override_module in .bazelrc.nix)
      flazelPath ? null,
      # Language-specific toolchain registration lines (e.g. --extra_toolchains)
      toolchainLines ? "",
      # Optional: additional setup for toolchain/libs (provided by language modules)
      extraSetup ? "",
    }:
    let
      bazelrc = pkgs.writeText "flazel-bazelrc.nix" (mkBazelrcContent {
        inherit toolchainLines flazelPath caches;
      });
    in
    ''
      # Create .nix-bazel-deps with writable caches
      rm -rf .nix-bazel-deps
      mkdir -p .nix-bazel-deps
      cp -rL ${caches.bazelRepoCache} .nix-bazel-deps/repo-cache
      cp -rL ${caches.bazelRegistryCache} .nix-bazel-deps/registry
      chmod -R u+w .nix-bazel-deps/repo-cache .nix-bazel-deps/registry

      # Framework bazelrc (override + non-BCR + toolchains). The build appends
      # the offline cache flags after this; the dev shell leaves it as-is.
      cp ${bazelrc} .nix-bazel-deps/.bazelrc.nix
      chmod u+w .nix-bazel-deps/.bazelrc.nix
      ${extraSetup}
    '';

  # Generic Bazel build derivation
  mkFlazelDerivation =
    {
      pkgs,
      name,
      src,
      caches,
      bazelCommand,
      installPhase,
      # Bazel package to use (defaults to latest stable)
      bazel ? pkgs.bazel,
      # Path to flazel source (auto-injected, used for --override_module in .bazelrc.nix)
      flazelPath ? null,
      # Optional: extra setup script (for language-specific toolchain/libs)
      extraDepsSetup ? "",
      # Language-specific toolchain registration lines for .bazelrc.nix
      toolchainLines ? "",
      nativeBuildInputs ? [ ],
      buildInputs ? [ ],
      runtimeDependencies ? [ ],
      bazelOutputBase ? "$TMPDIR/bazel-out",
    }:
    pkgs.stdenv.mkDerivation {
      inherit
        name
        src
        installPhase
        runtimeDependencies
        ;

      nativeBuildInputs = [
        bazel
        pkgs.coreutils
      ]
      ++ nativeBuildInputs;

      inherit buildInputs;

      buildPhase = ''
        export HOME=$TMPDIR
        ${mkFlazelDepsSetup {
          inherit
            pkgs
            caches
            flazelPath
            toolchainLines
            ;
          extraSetup = extraDepsSetup;
        }}
        # Point Bazel at pre-fetched caches (no network in Nix sandbox). These use
        # the sandbox-absolute path, so they are appended here, not in the shared
        # bazelrc content. --noenable_workspace lives in mkBazelrcContent so the
        # dev shell gets it too.
        echo "build --registry=file://$(pwd)/.nix-bazel-deps/registry" >> .nix-bazel-deps/.bazelrc.nix
        echo "build --repository_cache=$(pwd)/.nix-bazel-deps/repo-cache" >> .nix-bazel-deps/.bazelrc.nix
        bazel --output_user_root=${bazelOutputBase} ${bazelCommand}
      '';
    };
}
